[username]
style_root = "fg:white bg:#0078D4"
style_user = "fg:#0078D4 bg: white"
format = "[î‚¶](fg:#0078D4 bg:none)[$user]($style)[î‚°](fg:#0078D4 bg:none)"
disabled = false
show_always = false

[directory]
style = "fg:#FFFFFF bg:#0078D4"
format = "[î‚°](fg:#0078D4 bg:none inverted)[$path[$read_only]($style)]($style)[î‚°](fg:#0078D4 bg:none)"
read_only = "ï€£"
home_symbol = "~"
truncation_length = 3
truncation_symbol = "â€¦/"
truncate_to_repo = true
disabled = false

[azure]
style = "fg:#FFFFFF bg:#0078D4"
disabled = false
format = "[î‚°](fg:#012456 bg:#0078D4)[$symbol($subscription)]($style)[î‚°](fg:#0078D4 bg:none)"
symbol = "â˜ï¸ "

[dotnet]
symbol = "ğŸ¥… "
style = "green"
heuristic = false

[git_branch]
symbol = "ï˜ "
truncation_length = 4
truncation_symbol = ""

[docker_context]
format = "via [ğŸ‹ $context](blue bold)"

[terraform]
format = "[ğŸğŸ’¨ $workspace]($style) "

[kubernetes]
format = 'K8S: [$context \($namespace\)](bright white) '
disabled = true

[sudo]
style = "bold green"
symbol = "ğŸ‘©â€ğŸ’» "
disabled = false
allow_windows = true

[cmd_duration]
min_time = 500
format = "took [$duration](bold yellow)"
