[username]
style_root = "bold red"
style_user = "#FFFFFF"
format = "[î‚¶](fg:#0078D4 bg:#2C001E)[$user](bg:#0078D4)[î‚°](fg:#0078D4 bg:#2C001E)"
disabled = false
show_always = true

[directory]
style = "fg:#FFFFFF bg:#0078D4"
format = "[î‚°](fg:#2C001E bg:#0078D4)[$path[$read_only]($style)]($style)[î‚°](fg:#0078D4 bg:#2C001E)"
read_only = "ï€£"
home_symbol = " î—¿ ~"

[azure]
style = "fg:#FFFFFF bg:#0078D4"
disabled = false
format = "[î‚°](fg:#2C001E bg:#0078D4)[$symbol($subscription)]($style)[î‚°](fg:#0078D4 bg:#2C001E)"
symbol = "ï´ƒ "

[dotnet]
symbol = "ğŸ¥… "
style = "green"
heuristic = false

[git_branch]
symbol = "ğŸŒ± "
truncation_length = 4
truncation_symbol = ""

[docker_context]
format = "via [ğŸ‹ $context](blue bold)"

[terraform]
format = "[ğŸğŸ’¨ $workspace]($style) "

[kubernetes]
format = 'on [â›µ $context \($namespace\)](dimmed green) '
disabled = false

[sudo]
style = "bold green"
symbol = "ğŸ‘©â€ğŸ’» "
disabled = false
allow_windows = true

[cmd_duration]
min_time = 500
format = "took [$duration](bold yellow)"
